// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: data_transform_ui.proto

package turing_ui_data_transform

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadAndQueryArrowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName string `protobuf:"bytes,1,opt,name=tableName,proto3" json:"tableName,omitempty"`
	Query     string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	FilePath  string `protobuf:"bytes,3,opt,name=filePath,proto3" json:"filePath,omitempty"`
}

func (x *LoadAndQueryArrowRequest) Reset() {
	*x = LoadAndQueryArrowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_transform_ui_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadAndQueryArrowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadAndQueryArrowRequest) ProtoMessage() {}

func (x *LoadAndQueryArrowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_transform_ui_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadAndQueryArrowRequest.ProtoReflect.Descriptor instead.
func (*LoadAndQueryArrowRequest) Descriptor() ([]byte, []int) {
	return file_data_transform_ui_proto_rawDescGZIP(), []int{0}
}

func (x *LoadAndQueryArrowRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *LoadAndQueryArrowRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *LoadAndQueryArrowRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type LoadAndQueryArrowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SequencyNumber int32    `protobuf:"varint,1,opt,name=sequency_number,json=sequencyNumber,proto3" json:"sequency_number,omitempty"`
	Count          int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Data           [][]byte `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *LoadAndQueryArrowResponse) Reset() {
	*x = LoadAndQueryArrowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_data_transform_ui_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoadAndQueryArrowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadAndQueryArrowResponse) ProtoMessage() {}

func (x *LoadAndQueryArrowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_transform_ui_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadAndQueryArrowResponse.ProtoReflect.Descriptor instead.
func (*LoadAndQueryArrowResponse) Descriptor() ([]byte, []int) {
	return file_data_transform_ui_proto_rawDescGZIP(), []int{1}
}

func (x *LoadAndQueryArrowResponse) GetSequencyNumber() int32 {
	if x != nil {
		return x.SequencyNumber
	}
	return 0
}

func (x *LoadAndQueryArrowResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *LoadAndQueryArrowResponse) GetData() [][]byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_data_transform_ui_proto protoreflect.FileDescriptor

var file_data_transform_ui_proto_rawDesc = []byte{
	0x0a, 0x17, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d,
	0x5f, 0x75, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x74, 0x75, 0x72, 0x69, 0x6e,
	0x67, 0x2e, 0x75, 0x69, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x6f, 0x72, 0x6d, 0x22, 0x6a, 0x0a, 0x18, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x6e, 0x64, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x41, 0x72, 0x72, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22,
	0x6e, 0x0a, 0x19, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x6e, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41,
	0x72, 0x72, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32,
	0x92, 0x01, 0x0a, 0x0d, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72,
	0x6d, 0x12, 0x80, 0x01, 0x0a, 0x11, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x6e, 0x64, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x41, 0x72, 0x72, 0x6f, 0x77, 0x12, 0x32, 0x2e, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67,
	0x2e, 0x75, 0x69, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f,
	0x72, 0x6d, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x6e, 0x64, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41,
	0x72, 0x72, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x74, 0x75,
	0x72, 0x69, 0x6e, 0x67, 0x2e, 0x75, 0x69, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x6e, 0x64, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x41, 0x72, 0x72, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x30, 0x01, 0x42, 0x1a, 0x5a, 0x18, 0x74, 0x75, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x75,
	0x69, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_data_transform_ui_proto_rawDescOnce sync.Once
	file_data_transform_ui_proto_rawDescData = file_data_transform_ui_proto_rawDesc
)

func file_data_transform_ui_proto_rawDescGZIP() []byte {
	file_data_transform_ui_proto_rawDescOnce.Do(func() {
		file_data_transform_ui_proto_rawDescData = protoimpl.X.CompressGZIP(file_data_transform_ui_proto_rawDescData)
	})
	return file_data_transform_ui_proto_rawDescData
}

var file_data_transform_ui_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_data_transform_ui_proto_goTypes = []any{
	(*LoadAndQueryArrowRequest)(nil),  // 0: turing.ui.data_transform.LoadAndQueryArrowRequest
	(*LoadAndQueryArrowResponse)(nil), // 1: turing.ui.data_transform.LoadAndQueryArrowResponse
}
var file_data_transform_ui_proto_depIdxs = []int32{
	0, // 0: turing.ui.data_transform.DataTransform.LoadAndQueryArrow:input_type -> turing.ui.data_transform.LoadAndQueryArrowRequest
	1, // 1: turing.ui.data_transform.DataTransform.LoadAndQueryArrow:output_type -> turing.ui.data_transform.LoadAndQueryArrowResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_transform_ui_proto_init() }
func file_data_transform_ui_proto_init() {
	if File_data_transform_ui_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_data_transform_ui_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*LoadAndQueryArrowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_data_transform_ui_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LoadAndQueryArrowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_data_transform_ui_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_transform_ui_proto_goTypes,
		DependencyIndexes: file_data_transform_ui_proto_depIdxs,
		MessageInfos:      file_data_transform_ui_proto_msgTypes,
	}.Build()
	File_data_transform_ui_proto = out.File
	file_data_transform_ui_proto_rawDesc = nil
	file_data_transform_ui_proto_goTypes = nil
	file_data_transform_ui_proto_depIdxs = nil
}
